---
- ansible.builtin.set_fact:
    default_debian_distribution: "{{ ansible_distribution_release }}"
  when: default_debian_distribution is not defined

- name: debian | Installing pre-reqs
  ansible.builtin.apt:
    name:
      - lsb-release
    state: present

- name: debian | Install additional packages
  ansible.builtin.apt:
    pkg: "{{ backports_internal_additional_packages }}"
    state: present
  when: backports_internal_additional_packages | length > 0

- name: debian | Add backports repository
  when: debian_use_backports

  block:
    - name: Set debian release
      ansible.builtin.apt_repository:
        repo: deb {{ backports_internal_uri }} {{ ansible_distribution_release }}-backports {{ backports_internal_components }}
        state: present
        update_cache: true
    - name: Set backports
      ansible.builtin.set_fact:
        debian_release: '{{ default_debian_distribution + "-backports" }}'
- name: debian | Install zfs
  ansible.builtin.apt:
    name:
      - linux-headers-{{ ansible_kernel }}
      - zfsutils-linux
      - zfs-dkms
    state: present
    default_release: "{{ debian_release }}"

- name: debian | Enabling zfs module
  community.general.modprobe:
    name: zfs
    state: present

- name: debian | Installing open-iscsi (if enabled)
  ansible.builtin.apt:
    name:
      - open-iscsi
    state: present
  when: >
    zfs_enable_iscsi is defined and
    zfs_enable_iscsi

- name: debian | Un-installing open-iscsi (if not enabled)
  ansible.builtin.apt:
    name:
      - open-iscsi
    state: absent
  when: >
    zfs_enable_iscsi is defined and
    not zfs_enable_iscsi

- name: debian | Configuring iscsitarget service
  ansible.builtin.template:
    src: etc/default/iscsitarget.j2
    dest: /etc/default/iscsitarget
    owner: root
    group: root
    mode: "0644"
  notify:
    - restart iscsitarget
  when: >
    zfs_enable_iscsi is defined and
    zfs_enable_iscsi

- name: debian | Installing NFS (if enabled)
  ansible.builtin.apt:
    name: nfs-kernel-server
    state: present
  when: >
    zfs_enable_nfs is defined and
    zfs_enable_nfs

- name: debian | Un-installing NFS (if not enabled)
  ansible.builtin.apt:
    name: nfs-kernel-server
    state: absent
  when: >
    zfs_enable_nfs is defined and
    not zfs_enable_nfs

- name: debian | Configuring NFS Kernel Server
  ansible.builtin.template:
    src: etc/exports.j2
    dest: /etc/exports
    owner: root
    group: root
    mode: "0644"
  notify:
    - restart nfs-kernel-server
    - start zfs-share
  when: >
    zfs_enable_nfs is defined and
    zfs_enable_nfs

- name: debian | Configuring ZFS
  ansible.builtin.template:
    src: etc/default/zfs.j2
    dest: /etc/default/zfs
    owner: root
    group: root
    mode: "0644"
  notify:
    - start zfs-share
