---
# tasks file for ansible-zfs

- name: Set default values
  ansible.builtin.set_fact:
    zfs_install_update: true
  when: zfs_install_update is undefined

- name: Include Debian specific tasks
  ansible.builtin.include_tasks: debian.yml
  when: ansible_distribution == "Debian" and zfs_install_update

- name: Include Ubuntu specific tasks
  ansible.builtin.include_tasks: ubuntu.yml
  when: ansible_distribution == "Ubuntu" and zfs_install_update

- name: Encryption keys
  ansible.builtin.include_tasks: encryption_keys.yml
  when: >
    (zfs_create_pools or
    zfs_create_filesystems) and
    zfs_autoload_encryption_keys

- name: Include ZFS management tasks
  ansible.builtin.include_tasks: manage_zfs.yml

- name: Include Samba tasks
  ansible.builtin.include_tasks: samba.yml
  when: zfs_enable_samba

- name: Include ZFS tuning tasks
  ansible.builtin.include_tasks: tune_zfs.yml
  when: >
    zfs_enable_performance_tuning is defined and
    zfs_enable_performance_tuning

- name: Include Monitoring tasks
  ansible.builtin.include_tasks: monitoring.yml
  when: zfs_enable_monitoring
