---
- name: monitoring | Scheduling zpool scrubs
  ansible.builtin.cron:
    name: "{{ item.name }} zpool scrub"
    cron_file: zpool_scrub
    user: root
    minute: "{{ (item.scrub_cron | default(zfs_pools_scrub_cron)).minute | default(zfs_pools_scrub_cron.minute) }}"
    hour: "{{ (item.scrub_cron | default(zfs_pools_scrub_cron)).hour | default(zfs_pools_scrub_cron.hour) }}"
    day: "{{ (item.scrub_cron | default(zfs_pools_scrub_cron)).day | default(zfs_pools_scrub_cron.day) }}"
    month: "{{ (item.scrub_cron | default(zfs_pools_scrub_cron)).month | default(zfs_pools_scrub_cron.month) }}"
    weekday: "{{ (item.scrub_cron | default(zfs_pools_scrub_cron)).weekday | default(zfs_pools_scrub_cron.weekday) }}"
    job: /sbin/zpool scrub {{ item.name }}
  with_items: "{{ zfs_pools }}"
  when: >-
    item.scrub_cron is not defined or
    item.scrub_cron.enable is undefined or
    (item.scrub_cron.enable is defined and item.scrub_cron.enable)

# zfsutils-linux comes with a scrub cron job.
# It is removed if at least one zpool scrub is defined.
- name: monitoring | Removing zfsutils-linux cron job
  ansible.builtin.file:
    dest: /etc/cron.d/zfsutils-linux
    state: absent
  when: >-
    (zfs_pools
      | selectattr('scrub_cron', 'defined')
      | selectattr('scrub_cron.enable', 'defined')
      | selectattr('scrub_cron.enable', 'equalto', False)
      | list | length)
    < (zfs_pools | length)

- name: monitoring | Configuring ZFS monitoring
  ansible.builtin.template:
    src: opt/zfs_health_check.sh.j2
    dest: /opt/zfs_health_check.sh
    owner: root
    group: root
    mode: "0744"

- name: monitoring | Scheduling ZFS monitoring
  ansible.builtin.cron:
    name: zpool health check
    cron_file: zpool_health_check
    user: root
    minute: "*/20"
    job: /opt/zfs_health_check.sh
