---
- name: samba | Installing Samba
  ansible.builtin.apt:
    name: samba
    state: present
  when: ansible_os_family == "Debian"

- name: samba | Configuring Samba
  ansible.builtin.template:
    src: etc/samba/smb.conf.j2
    dest: /etc/samba/smb.conf
  notify: restart samba
