---
- name: ubuntu | Adding zfs ppa
  ansible.builtin.apt_repository:
    repo: "{{ zfs_ubuntu_ppa }}"
    state: present
  when: >
    ansible_distribution_version <= '14.04'

- name: ubuntu | Installing zfs ({{ ansible_distribution_version }} <= 14.04)
  ansible.builtin.apt:
    name: ubuntu-zfs
    state: present
  when: >
    ansible_distribution_version <= '14.04'

- name: ubuntu | Ensuring Ubuntu universe repo is enabled ({{ ansible_distribution_version }} >= 16.04)
  ansible.builtin.apt_repository:
    repo: deb {{ ubuntu_apt_repository }} {{ ansible_distribution_release | lower }} universe
    state: present
  when: >
    ansible_distribution_version >= '16.04'

- name: ubuntu | Installing zfs ({{ ansible_distribution_version }} >= 16.04)
  ansible.builtin.apt:
    name: zfsutils-linux
    state: present
  when: >
    ansible_distribution_version >= '16.04'

- name: ubuntu | Enabling zfs module
  community.general.modprobe:
    name: zfs
    state: present

- name: ubuntu | Installing iscsitarget (if enabled)
  ansible.builtin.apt:
    name:
      - iscsitarget
      - iscsitarget-dkms
    state: present
  when: >
    zfs_enable_iscsi is defined and
    zfs_enable_iscsi

- name: ubuntu | Un-installing iscsitarget (if not enabled)
  ansible.builtin.apt:
    name:
      - iscsitarget
      - iscsitarget-dkms
    state: absent
  when: >
    zfs_enable_iscsi is defined and
    not zfs_enable_iscsi

- name: ubuntu | Configuring iscsitarget service
  ansible.builtin.template:
    src: etc/default/iscsitarget.j2
    dest: /etc/default/iscsitarget
    owner: root
    group: root
    mode: "0644"
  notify:
    - restart iscsitarget
  when: >
    zfs_enable_iscsi is defined and
    zfs_enable_iscsi

- name: ubuntu | Installing NFS (if enabled)
  ansible.builtin.apt:
    name: nfs-kernel-server
    state: present
  when: >
    zfs_enable_nfs is defined and
    zfs_enable_nfs

- name: ubuntu | Un-installing NFS (if not enabled)
  ansible.builtin.apt:
    name: nfs-kernel-server
    state: absent
  when: >
    zfs_enable_nfs is defined and
    not zfs_enable_nfs

- name: ubuntu | Configuring NFS Kernel Server
  ansible.builtin.template:
    src: etc/exports.j2
    dest: /etc/exports
    owner: root
    group: root
    mode: "0644"
  notify:
    - restart nfs-kernel-server
    - start zfs-share
  when: >
    zfs_enable_nfs is defined and
    zfs_enable_nfs

- name: ubuntu | Configuring ZFS
  ansible.builtin.template:
    src: etc/default/zfs.j2
    dest: /etc/default/zfs
    owner: root
    group: root
    mode: "0644"
  notify:
    - start zfs-share

- name: ubuntu | Checking for ZFS-Auto-Snapshot package from the distribution
  ansible.builtin.command: apt-cache show zfs-auto-snapshot
  ignore_errors: true
  register: auto_snapshot
  when: zfs_enable_auto_snapshots
  changed_when: false
  failed_when: false
  check_mode: false

- name: ubuntu | Adding ZFS-Auto-Snapshot Repo
  ansible.builtin.apt_repository:
    repo: ppa:bob-ziuchkovski/zfs-auto-snapshot
    state: present
  when: >
    zfs_enable_auto_snapshots and
    auto_snapshot.stderr == 'E: No packages found'

- name: ubuntu | Installing ZFS-Auto-Snapshot
  ansible.builtin.apt:
    name: zfs-auto-snapshot
    state: present
  when: zfs_enable_auto_snapshots
